server:
  service:
    type: NodePort

extraScrapeConfigs: |
  - job_name: 'scaletestapp'
    metrics_path: /metrics
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: scaletestapp
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod
      - source_labels: [__meta_kubernetes_pod_ip]
        target_label: pod_ip
      - target_label: __address__
        replacement: $1:8080
        source_labels: [__meta_kubernetes_pod_ip]
